name: Upload Beta Addons

on:
  push:
    paths:
      - 'Beta/**'
  workflow_dispatch:

jobs:
  release-beta:   # <--- cambiar aquí
    runs-on: ubuntu-latest
    strategy:
      matrix:
        addon: ${{ fromJson('["ActionBarTweaks","OtroAddon"]') }}  # o dinámico con jq
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Copy addon to root
        run: |
          cp -r Beta/${{ matrix.addon }}/. .
          ls -la
          cat .pkgmeta
          cat *.toc

      - name: Run BigWigs Packager
        uses: BigWigsMods/packager@v2
        with:
          args: -g 11.0.5 -w 11.0.5 -p 1360857 -m .pkgmeta -n ${{ matrix.addon }}
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
